Make length of stock id configurable.
grocy/grocy pull request #1579
Opened 2021-08-15 08:12 UTC by lowlee

Stock id values are unique to their product, so the same value for two different products is fine. The values are generated using a strong hash, so for most instances 6 or 8 digits is enough to make the likelihood of collisions acceptably tiny, a value like 16 means we could generate unique entries for every tin of tomatoes ever made.

Why make it shorter? So you can print shorter grocycode barcodes. But probably not shorter than 6.

2021-08-15 08:34 UTC, berrnd commented
> Stock id values are unique to their product

That's wrong. The lookup "first by product id" only happens for grocycodes, in fact, the product part could be omitted for stock entry grocycodes to make it even shorter. [Here](https://github.com/grocy/grocy/issues/1061#issuecomment-716139435) is a short explanation about the ids used for stock entry relationship.

So I define a `STOCK_ID_LENGTH` of `1` or `2` and this still guarantees no collisions? I doubt it...

So would at least more checks related to that. I'm definitely not a fan of making own "uniqueness decisions", however, if it's about shortness, then the most short id would be most probably an own counter.

And this doesn't matter so much for 2D barcodes, `DataMatrix` is the prefered grocycode variant...

2021-08-15 08:56 UTC, berrnd commented
And I would say this doesn't need to be configurable, it just need to work, causes only confusion about what a stock_id is for and it's definitely not really required to dive into that topic for just using grocy...

2021-08-16 06:08 UTC, lowlee commented
Fair enough - This was an attempt to solve a problem we had with our setup that we thought might be useful for others stuck using a 1D barcode (due to only have a 1D scanner)

Also this was one change on the road to getting stockentry grocycodes to work

2021-08-17 16:28 UTC, berrnd requested changes
So as mentioned above:

- I don't think this need to be a config option, the shortest reasonable id is fine (so maybe an own counter)
  - Existing stock entry ids should be migrated

2022-03-13 19:00 UTC, berrnd commented
Looks outdated, so closing this - can be reopened anytime you like to continue on that.

2022-03-13 19:00 UTC, closed without merging